#!/bin/sh
case "$1" in
    configure)
                group='plex'
                if grep -q -E "$group(,.*|\b)" /etc/group; then
                        echo 'Group plex exists procceding with installation'
                else
                        echo 'Recreating user plex with group plex'
                        userdel plex
                        adduser --quiet --system --shell /bin/bash --home /var/lib/plexmediaserver plex --group
                        echo 'Setting correct permissions on plexmediaserver home, (this will take  a long time depending on your library size!)'
                        chown plex:plex /var/lib/plexmediaserver/ -R
                fi
        update-rc.d plexmediaserver defaults
        /etc/init.d/plexmediaserver stop
        /etc/init.d/plexmediaserver start
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

exit 0
